### PR TITLE
Remove newer versions from v1.1 release branch

### PR DESCRIPTION
**Pull request by camillobruni**

### CODE REVIEW

**Comment by smfr** [comment]
This looks like a mistake?

**Comment by camillobruni** [comment]
This is very intentional :).

You seem to have multiple versions per release branch which is quite unusal (see speedometer for instance).
This makes local checkouts and running more cumbersome than necessary (it's much easier to have the same path for all versions).

**Comment by camillobruni** [comment]
I'm not sure what the policy is here, but I'm mostly used to other projects (and this case specifically Speedometer) that don't use the mono-repo approach and have a single branch / tag per version. If this is a very intentional decision on the Motionmark side I'm all in to update all our tooling to deal with this.

**Comment by smfr** [comment]
Got it; you should have provided details in the opening comment.

I agree it's confusing that these older release branches have other versions in them, but please provide a PR with a useful commit message.

**Comment by jstenback** [comment]
FTR, I just submitted https://github.com/WebKit/MotionMark/pull/79 which is this same change with a description etc included.

**Pull request closed without merging**
