### PR TITLE
Fixes https://github.com/WebKit/MotionMark/issues/5 and creates 1.2.1

### PR DESCRIPTION
**Pull request by sky2**
As changing the complexity can impact scores, I increased the revision number. I believe Simon was suggesting this earlier.

### CODE REVIEW

**Comment by jrmuizel** [comment]
Long term I don't think we should be using different subdirectories for different versions. It makes it quite difficult to see what's being changed.

**Comment by sky2** [comment]
I agree with this makes it hard to see what actually changes. You can diff between the 1.2 and 1.2.1 directories, but that makes looking at history hard. What do we prefer here? I could apply the change in place in the 1.2 directory and update the version there.

**Comment by smfr** [comment]
Could you rebase this, or close it if it's already landed in https://github.com/WebKit/MotionMark/commit/f5d127cff37d174599ab4e954a6ebfbb7787aeb8

**Comment by bgrins** [comment]
Noting that I still don't understand the rationale behind this commit (https://github.com/WebKit/MotionMark/commit/f5d127cff37d174599ab4e954a6ebfbb7787aeb8). We have a thread going to discuss further.

**Comment by smfr** [comment]
I did some testing with totalRows = 68 and Safari's score was mostly unchanged, Chrome's increased by about 5%, and Firefox regressed by 20% just on this subtest.

**Comment by bgrins** [comment]
The first time I checked totalRows=68 in Firefox I hit a bogus-looking result: `965.92 -99.90% / +95.21% Confidence Interval: 1.00 - 1885.60`

**Comment by smfr** [comment]
Obviated by https://github.com/WebKit/MotionMark/commit/2b2e9d4e89dbd83922e7960872e8ad5f2d23d043

**Pull request closed without merging**
